// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu2RrmoxBsu5xGRmRT2LyBE11HJSebihw',
    appId: '1:827983270705:web:078c1acda14f1311c85610',
    messagingSenderId: '827983270705',
    projectId: 'prueba-f2fe6',
    authDomain: 'prueba-f2fe6.firebaseapp.com',
    storageBucket: 'prueba-f2fe6.appspot.com',
    measurementId: 'G-L3L5BDXM18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Hh9UES2OT0DsUtFKl0W1fFBpJTB5Ujs',
    appId: '1:827983270705:android:314e9b8e6c0fd51ac85610',
    messagingSenderId: '827983270705',
    projectId: 'prueba-f2fe6',
    storageBucket: 'prueba-f2fe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCXb2j3GLnExUSdHrfsJVyy4G0nd94NS8',
    appId: '1:827983270705:ios:9e06b8922a66d08ac85610',
    messagingSenderId: '827983270705',
    projectId: 'prueba-f2fe6',
    storageBucket: 'prueba-f2fe6.appspot.com',
    iosBundleId: 'com.example.pushLocalNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCXb2j3GLnExUSdHrfsJVyy4G0nd94NS8',
    appId: '1:827983270705:ios:9e06b8922a66d08ac85610',
    messagingSenderId: '827983270705',
    projectId: 'prueba-f2fe6',
    storageBucket: 'prueba-f2fe6.appspot.com',
    iosBundleId: 'com.example.pushLocalNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu2RrmoxBsu5xGRmRT2LyBE11HJSebihw',
    appId: '1:827983270705:web:d0b3a9d32446ce3dc85610',
    messagingSenderId: '827983270705',
    projectId: 'prueba-f2fe6',
    authDomain: 'prueba-f2fe6.firebaseapp.com',
    storageBucket: 'prueba-f2fe6.appspot.com',
    measurementId: 'G-85XYWMCFP7',
  );
}
